import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import "./globals.css";

const Titillium_WebSans = Titillium_Web({
  variable: "--font-Titillium_Web-sans",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={Titillium_WebSans.className}
      >
        {children}
      </body>
    </html>
  );
}
